# Generated by Django 3.1.2 on 2020-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Идентефикатор')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('intro_text', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('full_text', models.TextField(blank=True, db_index=True, verbose_name='Текст')),
                ('img', models.ImageField(upload_to='img/', verbose_name='Изображение')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
