# Generated by Django 3.1.2 on 2020-11-22 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess', '0003_auto_20201122_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='buyers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Покупатели'),
        ),
    ]
